2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] MongoDB starting : pid=14870 port=27018 dbpath=/home/nascherman/data/rs2 64-bit host=nascherman-UX305CA
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] db version v3.6.5
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] git version: a20ecd3e3a174162052ff99913bc2ca9a839d618
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] allocator: tcmalloc
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] modules: none
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] build environment:
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten]     distmod: ubuntu1604
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten]     distarch: x86_64
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten]     target_arch: x86_64
2018-07-13T17:11:06.285-0400 I CONTROL  [initandlisten] options: { net: { port: 27018 }, processManagement: { fork: true }, replication: { oplogSizeMB: 64, replSet: "m101" }, storage: { dbPath: "/home/nascherman/data/rs2", mmapv1: { smallFiles: true } }, systemLog: { destination: "file", path: "2.log" } }
2018-07-13T17:11:06.285-0400 W -        [initandlisten] Detected unclean shutdown - /home/nascherman/data/rs2/mongod.lock is not empty.
2018-07-13T17:11:06.286-0400 I -        [initandlisten] Detected data files in /home/nascherman/data/rs2 created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-07-13T17:11:06.286-0400 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2018-07-13T17:11:06.286-0400 I STORAGE  [initandlisten] 
2018-07-13T17:11:06.286-0400 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2018-07-13T17:11:06.286-0400 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2018-07-13T17:11:06.286-0400 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3314M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-07-13T17:11:07.518-0400 I STORAGE  [initandlisten] WiredTiger message [1531516267:518521][14870:0x7f47079989c0], txn-recover: Main recovery loop: starting at 2/4736
2018-07-13T17:11:07.518-0400 I STORAGE  [initandlisten] WiredTiger message [1531516267:518964][14870:0x7f47079989c0], txn-recover: Recovering log 2 through 3
2018-07-13T17:11:07.648-0400 I STORAGE  [initandlisten] WiredTiger message [1531516267:648974][14870:0x7f47079989c0], txn-recover: Recovering log 3 through 3
2018-07-13T17:11:07.729-0400 I STORAGE  [initandlisten] WiredTiger message [1531516267:729885][14870:0x7f47079989c0], txn-recover: Set global recovery timestamp: 0
2018-07-13T17:11:08.058-0400 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] 
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] 
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-07-13T17:11:08.058-0400 I CONTROL  [initandlisten] 
2018-07-13T17:11:08.075-0400 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/home/nascherman/data/rs2/diagnostic.data'
2018-07-13T17:11:08.075-0400 I REPL     [initandlisten] Did not find local voted for document at startup.
2018-07-13T17:11:08.076-0400 I REPL     [initandlisten] Rollback ID is 1
2018-07-13T17:11:08.076-0400 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2018-07-13T17:11:08.077-0400 I NETWORK  [initandlisten] waiting for connections on port 27018
2018-07-13T17:11:09.015-0400 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2018-07-13T17:11:35.767-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:37490 #1 (1 connection now open)
2018-07-13T17:11:35.786-0400 I NETWORK  [conn1] received client metadata from 127.0.0.1:37490 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.6.5" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "16.04" } }
2018-07-13T17:11:47.563-0400 I REPL     [conn1] replSetInitiate admin command received from client
2018-07-13T17:11:47.563-0400 W NETWORK  [conn1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2018-07-13T17:11:47.564-0400 I REPL     [conn1] replSetInitiate config object with 3 members parses ok
2018-07-13T17:11:47.565-0400 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27017
2018-07-13T17:11:47.565-0400 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:27019
2018-07-13T17:11:47.565-0400 I ASIO     [NetworkInterfaceASIO-Replication-0] Failed to connect to localhost:27017 - HostUnreachable: Connection refused
2018-07-13T17:11:47.565-0400 I ASIO     [NetworkInterfaceASIO-Replication-0] Dropping all pooled connections to localhost:27017 due to failed operation on a connection
2018-07-13T17:11:47.565-0400 W REPL     [replexec-0] Failed to complete heartbeat request to localhost:27017; HostUnreachable: Connection refused
2018-07-13T17:11:47.566-0400 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:27019, took 1ms (1 connections now open to localhost:27019)
2018-07-13T17:11:47.566-0400 E REPL     [conn1] replSetInitiate failed; NodeNotFound: replSetInitiate quorum check failed because not all proposed set members responded affirmatively: localhost:27017 failed with Connection refused
2018-07-13T17:11:47.567-0400 I NETWORK  [listener] connection accepted from 127.0.0.1:37500 #2 (2 connections now open)
2018-07-13T17:11:47.569-0400 I NETWORK  [conn2] received client metadata from 127.0.0.1:37500 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.6.5" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "16.04" } }
2018-07-13T17:12:05.051-0400 I NETWORK  [conn1] end connection 127.0.0.1:37490 (1 connection now open)
